### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#16]
Would be really nice to have a logo for the project :)

**Comment by RubenSandwich** [comment]
A few ideas to get the conversation started:

Blueprint:
![Blueprint](https://user-images.githubusercontent.com/1957315/60521004-67bd0d00-9cb4-11e9-883a-10adfd75ecc6.png)

Paint by Numbers:
![PaintByNumbers](https://user-images.githubusercontent.com/1957315/60521807-e0709900-9cb5-11e9-82d5-a33688eef3c5.png)

I was going for the theme of "already halfway done with the work". I want to convey to the developer that this tool makes it so much easier to upgrade that the update is already halfway done just by finding this tool. (I also believe that idea because I think this tool greatly simplifies the process of updating.)

If anyone wants to continue the work I started, here is my Sketch file:
[reactNativeUpdateLogo.zip](https://github.com/react-native-community/upgrade-helper/files/3350634/reactNativeUpdateLogo.zip)

**Comment by lucasbento** [comment]
Oh my god @RubenSandwich, those looks so damn cool!

I loved the `Blueprint w/ Background`, it looks so awesome.

What do you think @pvinis & @kelset?

**Comment by pvinis** [comment]
I love these!! I also prefer the blueprint with background the most. 💜 
(The idea for the number one is fun though.)

**Comment by KevinHu2014** [comment]
Those are freaking awesome! 

Love `Blueprint w/ Background` the most. ❤️

**Comment by kelset** [comment]
`Blueprint w/ Background` FTW ❤️

**Comment by RubenSandwich** [comment]
Thanks!

I'm just about to go on vacation. When I get back I'll touch up Blueprint w/ Background, turn it into an SVG and submit a pull request with it applied.

@pvinis I really wanted the Paint by Numbers one to work, but at the smaller size it becomes unreadable. Though I agree with you that it feels the most "fun".

**Comment by lucasbento** [comment]
@RubenSandwich: awesome, no rush, we will look forward for your PR 😄

Have a great vacation 🙂

**Comment by lucasbento** [comment]
Totally missed this, has been done on #56, very great job @RubenSandwich! 🤗
