### ISSUE TITLE
upgrade-helper files different to react-native init

### ISSUE THREAD

**Issue by Rebsos** [react-native-community/upgrade-helper#190]
Why is the package.json of upgrade-helper different to the package.json of react-native init?

## upgrade-helper / rn-diff-purge:

https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.60.6/RnDiffApp/package.json
```

{
  "name": "RnDiffApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.6"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.4.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

## npx react-native init rn_0_60_6 --version 0.60.6

```
{
  "name": "rn_0_60_6",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.6"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/runtime": "^7.5.0",
    "@react-native-community/eslint-config": "^0.0.3",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

- There are two more lines an almost every devDependency has a different version.
- Other react native versions are also affected

**Comment by pvinis** [comment]
Sometimes when init-ing, some dep versions get dynamically set (because of for example requiring ^1.2.3, so if there is 1.2.4 out when you run init you will get that), sometimes the diff generation runs a bit early or a bit late, so small differences could appear. It's normal.

The diff I see here is eslint, which is not really an important diff. If you use eslint, add it. If you don't, don't.

I will close this issue. If you have a specific problem or if you see any bigger changes that cause you some concern, please comment here or make a new issue. Thank you!
