### ISSUE TITLE
View/Download file with changed app name

### ISSUE THREAD

**Issue by pvinis** [react-native-community/upgrade-helper#208]
## Description

Let's take `package.json` as an example.

When I change the app name from the options popover, I can see that in the diff viewer the `"name"` is `"myApp"` for example, or whatever I put in the options.

When I click to view or download a file, the `"name"` in there is `"RnAppDiff"`, which makes sense, since it's just the original file.

## Discussion

I don't know if that is confusing or possibly causing trouble. I guess we could fix this by displaying the raw file after we have replaced the app name, like we do for the diff viewer, but is it worth it?

**Comment by benomatis** [comment]
Wouldn't you actually need to create the page with the app name in order to be able to display the contents of the original path? Alternatively we could do this with apache's mod_rewrite, then again that could become a quite complicated script.

And don't forget to think of not just the folder names in the path, but some file names have the app name as well, like many iOS files.

**Comment by pvinis** [comment]
Let's close this. This is not worth our time, not right now at least. There are more important things we can do in this repo and the upgrade story. :)

Maybe we can revisit in the future.
