### ISSUE TITLE
Add some color border or highlight on the comments

### ISSUE THREAD

**Issue by pvinis** [react-native-community/upgrade-helper#226]
# Feature Request
When quickly scanning this, the comment is almost invisible. When we look at a diff, we are looking for green and red, and white is just background noise.

<img width="1084" alt="Screen Shot 2020-03-30 at 15 51 57" src="https://user-images.githubusercontent.com/100233/77920361-acef8900-729e-11ea-8b3c-e4e9d4eac06f.png">

I think we should try to add some border that would make it pop more. Maybe a light blue or something that is not used in the diffs normally.

**Comment by thymikee** [comment]
Can we also show comments despite the file being collapsed? Or at least have a comment icon in some accent color, indicating there's something inside. Or both ideally. 

It's common that `. pbxproj` diff is collapsed by default and it contains instructions on how to make it work in Xcode. However, because the section is collapsed, most folks don't realize it's there.

**Comment by lucasbento** [comment]
I'll work on those!

**Comment by KevinHu2014** [comment]
Seems like it has been merge? 
Should we close this one?

**Comment by thymikee** [comment]
Yup, thanks!
