### ISSUE TITLE
Link not found

### ISSUE THREAD

**Issue by anasnmu** [react-native-community/upgrade-helper#285]
# Bug

gradle-wrapper.jar link not found

## React Native versions

updating from 0.63.4 to 0.65.1

## Steps to reproduce

https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.65.1

then go to gradle-wrapper.jar section. click the download icon, here's the link: https://github.com/undefined/raw/release/0.65.1/RnDiffApp/android/gradle/wrapper/gradle-wrapper.jar

Describe what you expected to happen:

1. the link should be working

**Comment by yfunk** [comment]
Seems related to #280 (cc: @lucasbento).

Looks like pressing `DownloadFileButton` for any binary file links to a broken URL (`https://github.com/undefined/[...]`), because `getBinaryFileURL()` is called without `packageName` [here](https://github.com/react-native-community/upgrade-helper/blob/93eac8f3490f02184b6763df506ce02ea0886eb9/src/components/common/DownloadFileButton.js#L15). 

Should be an easy fix 🙂
